name: Selenium IDE CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build_test:
        runs_on: ubuntu-latest
    
    steps:
     - name: Checkout the code
       uses: action/checkout@v3
    - name: .NET version 
       with:
        dotnet-version: 6
    - name: Install Chrome
     run: |
       sudo apt-get update
       sudo apt-get install -y google-chrome-stable
    - name: Install dependencies
      run: dotnet restore   
    - name: Build
      run: dotnet build --no-restore
    - name: Run tests
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: dotnet test --verbosity normal
      
